services:
  mongodb:
    container_name: micro_mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongovolume:/data/db  # Corrected volume path to /data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=arbaz
      - MONGO_INITDB_ROOT_PASSWORD=arbaz
    networks:
      - microservices-net
#    healthcheck:
#      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 3s

  mongo-express:
    container_name: micro_mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=arbaz
      - ME_CONFIG_MONGODB_ADMINPASSWORD=arbaz
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=arbaz  # Set basic auth username for web UI
      - ME_CONFIG_BASICAUTH_PASSWORD=arbaz  # Set basic auth password for web UI
    networks:
      - microservices-net
#    depends_on:
#      mongodb:
#        condition: service_healthy

  postgres:
    container_name: micro_postgresql
    image: postgres
    environment:
      POSTGRES_USER: arbaz
      POSTGRES_PASSWORD: password
      POSTGRES_DB: micro_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: micro_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - microservices-net
    restart: unless-stopped

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongovolume: